#include<bits/stdc++.h>
using namespace std;
char s[500135];
int qs[1000135],qt[1000135];
int main()
{
    int n,a,b,T,i,j,k;
    scanf("%d %d %d %d",&n,&a,&b,&T);
    scanf("%s",s+1);
    for(i=1;i<=n;i++)
    {
        s[n+i]=s[i];
    }
    int fst=1,lst=1,sum,mc=0;
    if(s[1]=='h')
        sum=1;
    else
        sum=1+b;
    for(i=n;i>=1;i--)
    {
        if(s[i]=='h')
            sum+=1+a;
        else
            sum+=1+a+b;
        if(sum>T)
        {
            fst=i+1;mc=max(mc,n-fst+2);
            break;
        }
    }
    printf("%d\n",mc);
    if(s[1]=='h')
        sum=1;
    else
        sum=1+b;
    for(i=2;i<=n;i++)
    {
        if(s[i]=='h')
            sum+=a+a;
        else
            sum+=1+a+b;
        if(sum>T)
        {
            lst=i-1;mc=max(mc,lst);
            break;
        }
    }
    if(s[1]=='h')
        sum=1;
    else
        sum=1+b;
    fst=n;
    int tmp;
    for(i=n;i>=1;i--)
    {
        if(sum<=T)
        {
            fst=min(fst,sum);
            if(s[i]=='h')
                sum+=1+a;
            else
                sum+=1+a+b;
            tmp=sum;
        }
        else
            break;
    }
    sum=tmp;
    for(lst=2;lst<=n;lst++)
    {
        if(s[lst]=='h')
            sum+=1+a*2;
        else
            sum+=1+a*2+b;
        while(sum>T)
        {
            if(s[fst]=='h')
                sum-=1+a;
            else
                sum-=1+a+b;
            fst++;
        }
        if(fst>n)
            break;
        mc=max(mc,lst+n-fst+1);
    }
    if(s[1]=='h')
        sum=1;
    else
        sum=1+b;
    fst=n;
    for(i=n;i>=1;i--)
    {
        if(sum<=T)
        {
            fst=min(fst,sum);
            if(s[i]=='h')
                sum+=1+2*a;
            else
                sum+=1+2*a+b;
            tmp=sum;
        }
        else
            break;
    }
    printf("fstlst = %d %d\n",fst,lst);
    sum=tmp;
    for(lst=2;lst<=n;lst++)
    {
        if(s[lst]=='h')
            sum+=1+a;
        else
            sum+=1+a+b;
        while(sum>T)
        {
            if(s[fst]=='h')
                sum-=1+2*a;
            else
                sum-=1+2*a+b;
            fst++;
        }
        if(fst>n)
            break;
        printf("%d %d %d\n",fst,lst,sum);
        mc=max(mc,lst+n-fst+1);
    }
    printf("%d\n",mc);
}
